name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.3
homepage: https://github.com/anicdh

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip32: 2.0.0
  bip39: 1.0.6
  bs58check: ^1.0.2
  hex: ^0.2.0
  pinenacl: ^0.6.0
  pointycastle: ^3.7.4

dev_dependencies:
  test: ^1.17.10
